Firma1/Models/Heslo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Firma1.Models
{
    public class Heslo
    {
        private string heslo = "Aa47Loi369";

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        public bool ZvalidujHeslo()
        {
            if (Password == heslo)
            {
                return true;
            }

            return false;
        }
    }

    
}

Firma1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Firma1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            string nazev = "";
            int pocet1 = 1;
            int pocet2 = 1;
            int vyber1=0;
            int vyber2=0;
            bool stop = true;
            List<string> tabulka = new List<string>();
            using (StreamReader sr = new StreamReader(Server.MapPath("~/temp/PURTDELI.inc")))
            {

                string s;
               
                    while (stop)
                    {
                    s = sr.ReadLine();

                    if (s.Contains("STRUCTURE"))
                    {
                        Match match = Regex.Match(s, @"(?<=\()(.*?)(?=\))");
                        if (match.Success)
                        {
                            string value = match.Groups[0].Value;
                            nazev = value;
                        }
                        
                    }

                        if (s.TrimStart().StartsWith("("))
                        {

                            vyber1 = pocet1;
                        }

                        if (s.EndsWith(";"))
                        {

                            vyber2 = pocet1;
                            stop = false;
                            
                        }
                        pocet1 += 1;
                    }
                
            }
            using (StreamReader sr = new StreamReader(Server.MapPath("~/temp/PURTDELI.inc")))
            {

                string s;
                while ((s = sr.ReadLine()) != null)
                {
                    if (pocet2 >= vyber1)
                    {
                        if (pocet2 <= vyber2)
                        {
                            tabulka.Add(s);
                        }
                    }
                    pocet2 += 1;
                }
            }
            
            string crtable = "CREATE TABLE "+nazev;
            foreach (string s in tabulka) {
                crtable += s;
                }            
           

            using(SqlConnection connection=new SqlConnection("Data Source=localhost\\SQLEXPRESS;Initial Catalog=Transakce1;Integrated Security=True"))
            {
                SqlCommand command = new SqlCommand(crtable, connection);
                command.Connection.Open();
                try
                {
                    command.ExecuteNonQuery();
                }
                catch
                {

                }
            }
            ViewBag.Tabulka = tabulka;
            return View();
        }

        public ActionResult ONas()
        {
            return View();
        }

        public ActionResult Kontakt()
        {
            return View();
        }

        public ActionResult WebPages()
        {
            return View();
        }

        public ActionResult WebApp()
        {
            return View();
        }
    }
}

Firma1/Controllers/LoginController.cs
using Firma1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Firma1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            Heslo heslo = new Heslo();
            return View(heslo);
        }

        [HttpPost]
        public ActionResult Index(Heslo heslo)
        {

            
             if(heslo.ZvalidujHeslo())   
            return RedirectToAction("Index","Home");
            return View(heslo);
        }
    }
}

Firma1/Controllers/TransakceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Firma1.Controllers
{
    public class TransakceController : Controller
    {
        // GET: Transakce
        public ActionResult Index()
        {
            List<string> list = new List<string>();
            /* list.Add("PURSP001");
             list.Add("02");
             list.Add("01");
             list.Add("PURCHASING SYSTEM        PRICE AND SUPLIER MENU");
             list.Add("02");
             list.Add("18");
             list.Add(DateTime.Now.ToShortDateString());
             list.Add("02");
             list.Add("70");
             list.Add(DateTime.Now.ToLongTimeString());
             list.Add("03");
             list.Add("70");
             list.Add("JOB CODE =");
             list.Add("03");
             list.Add("01");
             */
            string cesta = Server.MapPath("~/temp/Transakce.txt");
            using (StreamReader sr = new StreamReader(cesta))
            {
                list.Clear();
                string s;
                while ((s = sr.ReadLine()) != null)
                {
                    if (s.Contains("DFLD") && !s.Contains("CDATE") && !s.Contains("CTIME") && !s.Contains("NUMBER") && !s.Contains("MSG"))
                    {
                        Match match=Regex.Match(s,@"(?<=')[^']*(?=')");
                        if (match.Success)
                        {
                            string value = match.Groups[0].Value;
                            list.Add(value);
                        }

                        
                        
                    }

                   

                    if (s.Contains("CDATE"))
                    {
                        
                            list.Add(DateTime.Now.ToShortDateString());
                        
                    }

                    if (s.Contains("CTIME"))
                    {
                        list.Add(DateTime.Now.ToLongTimeString());
                    }

                    if (s.Contains("NUMBER"))
                    {

                        list.Add("?");

                    }

                    if (s.StartsWith("MSG"))
                    {
                        int index = s.IndexOf("POS=");
                        
                        string v1 = s.Substring(index + 5, 2);
                        string v2 = s.Substring(index + 8, 2);
                        list.Add("?");
                        list.Add(v1);
                        list.Add(v2);
                        list.Add("WHITE");
                        break;
                    }

                    if (s.Contains("POS="))
                    {
                        int index = s.IndexOf("POS=");
                        string v1 = s.Substring(index + 5, 2);
                        string v2 = s.Substring(index + 8, 2);
                        list.Add(v1);
                        list.Add(v2);
                    }
                   
                    if (s.Contains("EATTR=") && s.Contains("POS="))
                    {
                        int index = s.IndexOf("EATTR=");
                        string v1 = s.Substring(index + 8,7);
                        int index1 = v1.IndexOf(")");
                       v1 = v1.Substring(0, index1);
                        if (v1 == "TURQ")
                        {
                            v1 = "TURQUOISE";
                        }
                        if (v1 == "PINK")
                        {
                            v1 = "GREEN";
                        }
                        list.Add(v1);
                    }
                    else if(s.Contains("POS=") && !s.Contains("EATTR="))
                    {
                        list.Add("RED");
                    }

                    
                }

    

            }
            ViewBag.A = list;
            
            return View();
        }
    }
}

Firma1/Views/Home/Index.cshtml
@{ 
    List<string> list = ViewBag.Tabulka;
}

<div>@{
    foreach (string s in list)
    {
        @s<br/>
    }
}</div>

<div class="jumbotron">
    <h1>Tvoříme webové aplikace</h1>
    <p class="lead">Tvoříme jednoduché a moderní webové stránky a aplikace na míru v .Netu</p>

</div>

<div class="row marketing">
    <div class="col-lg-6">
        <a href="@Url.Action("WebPages","Home")"><h4>Webové stránky</h4></a>
        <p>Tvoříme moderní, jednoduché a přehledné webové stránky, které zaujmou každého návštěvníka.</p>

        <h4>Subheading</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

        <h4>Subheading</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>

    <div class="col-lg-6">
        <a href="@Url.Action("WebApp","Home")"><h4>Webové aplikace</h4></a>
        <p>Vyvíjíme webové aplikace na zakázku. Od informačních systémů až po aplikace pro analýzu dat.</p>

        <h4>Subheading</h4>
        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

        <h4>Subheading</h4>
        <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
</div>

Firma1/Views/Home/Kontakt.cshtml
<div class="jumbotron">
    <h2>Kontakt</h2><br />
    Jméno: Daniel Pokorný<br />
    Adresa:Antuškova 1139
    Benešov  25601
    mobil: 720340701
    email: danpokorny01@gmail.com
</div>



 

Firma1/Views/Home/ONas.cshtml
<div class="jumbotron">
    <h1>O nás</h1>
    <p class="lead">Navrhujeme a tvoříme webové stránky a webprezentace, internetové eshopy a online katalogy, webové aplikace a online systémy. Vždy podle potřeb klienta tak, aby správa webové prezentce byla co nejvíce automatizována. Jedině taková řešení zajistí, že nevznikne následně problém s lidským prvkem. Je tak jasné, že bude vše pracovat ihned, bez odmlouvání a bez potřeby pauz a odpočinku. Každý náš klient má možnost výběru variant řešení podle toho, jestli se chce o svůj webový systém starat sám nebo nechá tuto práci na nás.</p>

</div>

Firma1/Views/Home/WebApp.cshtml
<div class="jumbotron">
    <h1>Webové aplikace</h1>
    <p class="lead">VYVÍJÍME WEBOVÉ APLIKACE NA ZAKÁZKU

Zabýváme se také tvorbou internetových aplikací na míru, podle přání klienta. Nejčastěji se jedná o informační systém malého rozsahu, databázové aplikace a redakční systémy:

webové aplikace na zakázku, informační systémy malého rozsahu
redakční, evidenční systémy a systémy pro archivaci dokumentů
zpracování návrhu webového projektu (schéma, technické specifikace)
aplikace pro analýzu dat, databázové aplikace
grafické - interaktivní mapy objektů</p>
</div>

Firma1/Views/Home/WebPages.cshtml
<div class="jumbotron">
    <h1>Webové stránky</h1>
    <p class="lead">Tvoříme moderní, jednoduché a přehledné webové stránky, které zaujmou každého návštěvníka. Pokud přemýšlíte nad webovými stránkami, kontakujte nás pro konzultaci zdarma. Nejdříve vyslechneme Vaše požavky a následně zpracujeme ideální návrh. Vytvoříme grafický design tak, aby odpovídal Vašim představám a podkladům. Následně webové stránky vyplníme obsahem, připojíme web k redakčnímu systému a kompletně se postaráme o provoz webu.</p>
</div>

Firma1/Views/Login/Index.cshtml
@using Firma1.Models
@model Heslo
 
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="@Url.Content("~/Content/log.css")" rel="stylesheet">
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
            <form class="form-signin">
                
                @Html.PasswordFor(m => m.Password) 

                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Přihlásit</button>
            </form><!-- /form -->
           
        </div><!-- /card-container -->
    </div><!-- /container -->
    }
</body>
</html>

Firma1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Narrow Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">

    

    <!-- Custom styles for this template -->
    <link href="@Url.Content("~/Content/styl.css")" rel="stylesheet">

   

    
</head>

<body>

    <div class="container">
        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation" class="active"><a href="@Url.Action("Index","Home")">Domů</a></li>
                    <li role="presentation"><a href="@Url.Action("ONas","Home")">O nás</a></li>
                    <li role="presentation"><a href="@Url.Action("Kontakt","Home")">Kontakt</a></li>
                    <li role="presentation"><a href="@Url.Action("Index","Transakce")">Transakce</a></li>
                </ul>
            </nav>
            <h1 class="text-muted">IDPOK</h1>
        </div>

       
        @RenderBody()
        <footer class="footer">
            <p>&copy; 2016 Company, Inc.</p>
        </footer>

    </div> <!-- /container -->
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
</body>
</html>

Firma1/Views/Transakce/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;

    int zaklPoz = 01;
    int p = 0;
    List<string> lisst = ViewBag.A;

}
<body style="background-color:black"></body>
<h1 style="color:blue;text-align:center;margin-top:30px">TRANSAKCE</h1>
 <div style="position:absolute;left:320px">

    @{
        int poz;

        for (int i = 0; i < lisst.Count(); i = i + 4)
        {
            poz = int.Parse(lisst[i + 1]);
            if (poz > zaklPoz)
            {
                { <br />}
            }


            {


                <span style="color:@lisst[i+3];font-size:large;position:absolute;top:@(25 * (int.Parse(lisst[i + 1])) + "px");left:@(8 * (int.Parse(lisst[i + 2])) + "px")">
                    @if (lisst[i] == "?")
                    {
                        { <br/><input type="text" style="width:60px;margin-top:-5px"/>}
                    }

                    else
                    {<pre>@lisst[i]</pre>}

                </span>

            }
            zaklPoz = poz;
        }
    }
</div>